spring:
  application:
    name: sample-job-shell

server:
  port: 0

eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}   
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  
meta:
  admin-url: http://127.0.0.1:9090/
  host-address: 127.0.0.1
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/jside
    username: ENC(yxN/mqqITFXs1Hk8nf1a8g==)
    password: ENC(aDlF1/UeXM7pdKxjER25pczJ0Qd2Dywy)

job01:
  name: DEV-SHELL-JOB-01
  desc: "The First Shell Job@DEV"
  mode: trigger
  cron: "0 0/10 * * * ?"
  file:
    script: "D:/data/one-shell.bat"

job02:
  name: DEV-SHELL-JOB-02
  desc: "2nd shell job at DEV"
  mode: self
  cron: "0 0/5 * * * ?"
  file:
    script: "D:/data/two-shell.bat"
